name: "CI - MongoDB-Atlas-On-AWS"

on:
  push:
    branches:
    - master
  pull_request:
   # matches pull request for all branches and tag names
    
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      DEV: 'yes'
      PROD: 'no'
      APPLY: 'yes'
      DESTROY: 'no'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
      MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
    defaults:
      run:
        shell: bash
 
    steps:
    - name: GitHub Actions Runner Set-up
      uses: actions/checkout@v2
      
    - name: Terraform CLI Set-up
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Security Scan Set-up
      uses: triat/terraform-security-scan@v3
        
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Variables - Dev
      if: ${{ env.DEV == 'yes' }}
      run: |-
        cat dev.auto.tfvars <<EOF
        EOF
        
    - name: Terraform Variables - Prod
      if: ${{ env.PROD == 'yes' }}
      run: |-
        cat prod.auto.tfvars <<EOF
        EOF
    
    - name: Terraform Plan
      run: terraform plan
      
    - name: Terraform Apply
      #if: github.ref == 'refs/heads/main' && github.event_name == 'push' && env.APPLY == 'yes'
      if: github.event_name == 'push' && env.APPLY == 'yes'
      run: terraform apply -auto-approve
  
    - name: Terraform Destroy
      if: ${{ env.DESTROY == 'yes' }}
      run: terraform destroy -auto-approve
