name: "MongoDB-Atlas-Migration-On-AWS"

on:
  push:
    branches:
    - main
  pull_request:
   # matches pull request for all branches and tag names
    
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      APPLY: 'no'
      DESTROY: 'no'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
      MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
    defaults:
      run:
        shell: bash
 
    steps:
    - name: GitHub Actions Runner Set-up
      uses: actions/checkout@v2
      
    - name: GitHub Security Scan Set-up
      uses: triat/terraform-security-scan@v1
        
    - name: Terraform CLI Set-up
      uses: hashicorp/setup-terraform@v1
        
    - name: Terraform Variables
      run: |-
        cat dev.auto.tfvars <<EOF
        EOF
      
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Validate
      # validate GitHub Actions workflow config
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan
      
    - name: Terraform Apply
      #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      if: ${{ env.APPLY == 'yes' }}
      run: terraform apply -auto-approve
      
    - name: Terraform Destroy
      if: ${{ env.DESTROY == 'yes' }}
      run: terraform destroy -auto-approve
